### ISSUE TITLE
Plum binding sleeping process cause openHAB to lockup

### ISSUE THREAD

**Issue by billmans** [mikenemat/org.openhab.binding.plum#5]
First, this binding is fantastic! :-)

I have noticed 2 things and I think they are related.  First if I try to shutdown/restart openHAB I get an error messages in the console about sleeping threads for PLUM.  The result is I need to reboot the server every time to restart.  I have tried waiting but its almost like the plum binding just never shuts down.

Second, similar error.  My openHAB server is on a UPS, and lightpads are not.  When I have a power failure seems openHAB goes nuts trying to contact/connect to the lightpads to the point it seems to hang openHAB (i will try to force this again and copy the errors) but they are similar to the sleeping thread error message I see above.  (BTW, this is a brief power failure that causes the lightpads to restart almost instantly, but the server does not seem to reconnect)

The first part (rebooting) works, the concern is the power failure as when this happens and I am not there openHAB is now down until I am able to restart the server.

B

**Comment by mikenemat** [comment]
Thanks for the report. I have indeed observed this issue but I wasn't aware of the various ways it can impact OpenHAB. I believe I know how to fix it. Stay tuned. Might be able to get a new build out in the next week or two.

**Comment by billmans** [comment]
Thanks! that sounds great!  I will keep an eye, and let me know if there is any info/testing I can do to help out!

Bill

**Comment by billmans** [comment]
Hi Mike, just checking in to see if you had anymore thoughts on this.  Would love to see this lockup error go away, and the ability to control the LED colours based on rules would be cool! :-)

**Comment by mikenemat** [comment]
Sorry for the late reply. I'm in a critical stage of a lengthy home reno
project and I'd be lying if I said I could get to this any time soon. I had
hoped to, but things aren't going nearly as smoothly as planned. Perhaps
someone else can fork the codebase and help, otherwise maybe in another few
weeks I might have a chance.

**Comment by billmans** [comment]
Hi Mike, thought I would check in and see if you have any plans to update the plum binding for openhab 2.2?  I am still using it in legacy mode, but its starting to throw more and more errors!  I don't know what I would do without it now!  I may throw it out to the forums to see if anyone could help with and update to 2.2.

**Comment by mikenemat** [comment]
Hey Bill,

I know it has been a while, but I’m going to try and get focused back on this. I’ll see if I can get a OpenHAB 2.2 Dev environment up and running… I’m fairly familiar with the errors you are referring to. I’ll let you know if I succeed.

- Mike

**Comment by salanki** [comment]
I’m happy to donate some $ for your efforts!

**Comment by mikenemat** [comment]
Hey guys. Offers for donations are appreciated but not at all necessary.

I just got a OpenHAB 2.2 install up and running with the Plum Plugin. Porting this to a "native" OpenHAB 2.x plugin is a long term goal. In the short term, I want to get it working in legacy mode without errors.

I don't see any errors at all related to OpenHAB 2.2? However, I'm aware of the general instability issues related to starting/stopping, and less-than-graceful handling of lightpads that aren't reachable on the network.

If I was to fix these specific issues, is that sufficient enough for you guys to continue using it in compat/legacy mode? I'm personally not aware of any errors being thrown that aren't related to those two issues?

Regarding those two specific issues.

**Start/stop:** I have a multithreaded TCP event streaming implementation which allows for real-time event processing from the lightpads instead of polling. Admittedly, I hacked this together without appreciating the nuances of running threads in OpenHAB. This should be a matter of handling thread interrupts correctly - not a huge deal. I'm working on it now. The goal is to stop them gracefully.

**Graceful handling of unreachable lightpads**: This one is a bit trickier. We need to periodically retry connectivity to the event stream from the lightpads. Right now, the retry functionality is broken. Sorry!. It was an obvious bug, and I think I've fixed it. I will set a 5-second retry interval. I think this is a good compromise. Instead of getting giant stack traces in your error logs, you will also get a nice clean error in a single line.

Also, a lot of errors you see in the logs aren't really errors. In many cases, the plugin is actually retrying things properly, but generating a ton of unnecessary and scary logging output. I'm going to clean up some of the error handling and log output to avoid being unnecessarily verbose.

Let me know if this sounds OK or if I've missed another issue you guys are experiencing...

**Comment by mikenemat** [comment]
Please try https://github.com/mikenemat/org.openhab.binding.plum/blob/master/target/org.openhab.binding.plum-1.11.0-OPENHAB_2_0.jar and let me know if this helps.

**Comment by mikenemat** [comment]
Reopening until I get confirmation that it has been fixed :)

**Comment by billmans** [comment]
Hi Mike, Thanks so much for working on this! I installed the new jar on openHAB 2.2 and so far looks good.  Everything that was working before still works, I will test the shutdown / power loss stuff tomorrow.  

I have noticed the light switch issue, they are all on DHCP reservations so I know who is who.  I was unable to use the air gap before without restarting the whole system, will test this moving forward.  

I use the motion sensor on the lightpads to trigger all sorts of rules, including on/off of the lightpad loads, for the most part it works fantastic other than the odd fantom detection of motion!  I like having the real time processing instead of the polling as this would add delays I imagine.

Thanks again!

**Comment by mikenemat** [comment]
Awesome! Let me know if the shutdown stuff works and I’ll close this issue!

**Comment by mikenemat** [comment]
New build. Cleaned up logging a bit more and made timeouts obvious. Also got rid of the TCP Stream events in the log. You can still see them if you start OpenHAB in debug mode, but INFO-level was too noisy. They are DEBUG level now. 

https://github.com/mikenemat/org.openhab.binding.plum/blob/master/target/org.openhab.binding.plum-1.11.0-OPENHAB_2_0.jar

**Comment by mikenemat** [comment]
Closing since no reply provided
